# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Blog"
url = "blog/"
weight = 3

[[main]]
name = "Publications"
url = "publications/"
weight = 4

[[main]]
name = "Resources"
url = "resources/"
weight = 5

[[main]]
weight = 6
name = "Resources"
hasChildren = true

  [[main]]
  parent = "Resources"
  name = "1. Health Navigation"
  url = "health-navigation/"
  weight = 1

  [[main]]
  parent = "Resources"
  name = "2. Platform Details"
  url = "platform-details/"
  weight = 2

  [[main]]
  parent = "Resources"
  name = "3. Open Source Guidelines"
  url = "open-source-guidelines/"
  weight = 3

[[main]]
name = "Terms & Conditions"
url = "terms-and-conditions/"
weight = 7
  
[[main]]
name = "Contact"
url = "contact/"
weight = 8


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Blog"
url = "blog/"
weight = 2

[[footer]]
name = "Blog Details"
url = "blog/post-1/"
weight = 3

[[footer]]
name = "Terms & Conditions"
url = "terms-and-conditions/"
weight = 4